### ISSUE TITLE
possible new NPM package

### ISSUE THREAD

**Issue by artola** [relay-tools/relay-compiler-language-typescript#104]
@alloy I am very interested to get the just introduced improvement "Generate a discriminated union whenever possible". Could be possible to release a new NPM package?

I mean if the code is stable, by the way the build now show some error that I do not know if it is related.

**Comment by alloy** [comment]
I’m on vacation the coming two weeks. @zephraph could you spare a moment to look into why deploying fails?

**Comment by artola** [comment]
@zephraph It seems to be a problem with [rate-limit](https://developer.github.com/v3/#rate-limiting)

```
// https://api.travis-ci.org/v3/job/521006783/log.txt
{ HttpError: API rate limit exceeded for user ID 2320.
     'x-ratelimit-limit': '30',
     'x-ratelimit-remaining': '0',
     'x-ratelimit-reset': '1555459499',
```
The error shows that the reset was set to: Wed Apr 17 2019 02:04:59 GMT+0200 (Central European Summer Time).

could be enough to retry a build ?

**Comment by zephraph** [comment]
@artola there's an issue with `auto`, the tool we're using for releases. 

I've got a [PR](https://github.com/intuit/auto/pull/335) to fix it, but I'm waiting on the maintainers to review and merge. 

As soon as that's merged I'll rerun the build and it should publish a new version. If that doesn't work we'll have to wait for @alloy to get back from vacation to manually deploy.

**Comment by zephraph** [comment]
@alloy all the auto issues fixed, but it looks like we have a GitHub permissions issue. Let's try to sort it out when you get back. 

@artola it looks like the updates were published to NPM though.

**Comment by artola** [comment]
@alloy this discriminated unions are awesome!!! @zephraph Thanks. The package is perfect!
