### ISSUE TITLE
Supporting customScalar from https://github.com/facebook/relay/pull/2745

### ISSUE THREAD

**Issue by andres-valdes** [relay-tools/relay-compiler-language-typescript#121]
https://github.com/facebook/relay/pull/2745 added support for customScalars, is it possible to do something similar here?

**Comment by sibelius** [comment]
Please send a PR

**Comment by kastermester** [comment]
@andres-valdes What exactly is it you are missing from this? I'm using the newest TS plugin with relay-compiler 5.0 and having no issues using the CLI option.

**Comment by alloy** [comment]
This should be supported via those upstream changes, as per @kastermester’s comment. Closing this in absence of any follow-up.
