### ISSUE TITLE
customScalar doesn't support `any`

### ISSUE THREAD

**Issue by itajaja** [relay-tools/relay-compiler-language-typescript#129]
is there a reason why `any` [is not supported in custom scalars](https://github.com/relay-tools/relay-compiler-language-typescript/blob/ccb6e3d2dd44617726e2d13df8ae718afa46ab0b/src/TypeScriptTypeTransformers.ts#L78)? a reasonable use case is the use of the JSON scalar:

https://github.com/taion/graphql-type-json

if there are no objections, I'll push a PR

**Comment by alloy** [comment]
Resolved with #126
