### ISSUE TITLE
ClientExtension TSC error in generated files: missing type and other required fields

### ISSUE THREAD

**Issue by BruceL33t** [relay-tools/relay-compiler-language-typescript#131]
When I try to extend Query with local client state, like suggested in these links:

https://babangsund.com/relay_local_state_management_2/
https://stackoverflow.com/a/57649863/3973406

the compiler will generate the relay files without errors, but if I run the TypeScript compiler I get errors in the relay generated files.

```
    {
        "kind": "ClientExtension",
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "name": "clientState",
            "storageKey": null,
            "args": null,
            "concreteType": "ClientState",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "name": "showToggleButton",
                "args": null,
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "name": "eventsCount",
                "args": null,
                "storageKey": null
              }
            ]
          }
        ]
      }
```

Seems like the error is cause by the ConcreteRequest interface from @types/relay-runtime:

![image](https://user-images.githubusercontent.com/15261407/63810960-71669800-c926-11e9-8ce5-95bb2fd88e5f.png)

**Comment by BruceL33t** [comment]
Sorry I do not know flow.

But I found out that if I replace

`
"operation": {
    "kind": "Operation",
    "name": "AppQuery",
    "argumentDefinitions": [],
    "selections": [
      (v2/*: any*/),
      {.......
`

with 

`
"operation": {
    "kind": "Operation",
    "name": "AppQuery",
    "argumentDefinitions": [],
    "selections": [
      (v2 as any),
      {.......
`

it will resolve the compile errors with `v2 as any` instead of `v2/*: any*/` which is generated when running the relay compiler

**Comment by sorenhoyer** [comment]
A quick temporary workaround could be to 
1. put https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/relay-runtime/index.d.ts in a local @types/relay-runtime.d.ts file 
2. inside a declare module "relay-runtime" {} 
3. and just search/replace every "declare " inside it with "" (nothing).

Then make these changes to the file:

```
export interface NormalizationLinkedField {
  readonly kind: string; // 'LinkedField';
  readonly alias?: string | null | undefined;
  readonly name?: string;
  readonly storageKey?: string | null | undefined;
  readonly args?: ReadonlyArray<NormalizationArgument>;
  readonly concreteType?: string | null | undefined;
  readonly plural?: boolean;
  readonly selections?: ReadonlyArray<NormalizationSelection>;
}
```

```
interface ReaderInlineFragment {
  readonly kind: string; // 'InlineFragment';
  readonly selections: ReadonlyArray<ReaderSelection>;
  readonly type?: string;
 }
```

If you wonder what changed, it's just setting the types to optional with `?` - thus a temporary workaround.

**Comment by alloy** [comment]
Could you please provide an example project that exhibits the problem?

**Comment by renanmav** [comment]
Here https://github.com/renanmav/local-store-repro

**Comment by alloy** [comment]
Thanks, will try to get to it asap!

**Comment by artola** [comment]
@alloy This code is from Relay repo (Flow), it shows that the function `generateClientExtension` generates the code in the same way that TS, the difference is that `ReaderSelection` also includes the type `ReaderClientExtension` that is missing in the TS typings.

```javascript
// relay: flow

function generateClientExtension(node: ClientExtension): ReaderSelection {
  return {
    kind: 'ClientExtension',
    selections: generateSelections(node.selections),
  };
}

...

export type ReaderSelection =
  | ReaderCondition
  | ReaderClientExtension
  | ReaderField
  | ReaderFragmentSpread
  | ReaderInlineDataFragmentSpread
  | ReaderInlineFragment
  | ReaderModuleImport;

...
// missing (for my case) !!!
export type ReaderClientExtension = {|
  +kind: 'ClientExtension',
  +selections: $ReadOnlyArray<ReaderSelection>,
|};

// missing ???
export type ReaderModuleImport = {|
  +kind: 'ModuleImport',
  +documentName: string,
  +fragmentPropName: string,
  +fragmentName: string,
|};
```
While in `@types/relay-runtime` we have just:

```typescript
export type ReaderSelection =
  | ReaderCondition
  | ReaderField
  | ReaderFragmentSpread
  | ReaderInlineFragment
  | ReaderMatchField; // ??? no idea
```

**Comment by alloy** [comment]
@artola Great sleuthing 👌  I’m sure other things are missing, but I wouldn’t go down the rabbit hole of trying to cover everything too much, just PR to the DefinitelyTyped typings what you need now to fix your case.

**Comment by renanmav** [comment]
Looks like it was fixed

Thanks a lot @artola
