### ISSUE TITLE
Always capitalise types?

### ISSUE THREAD

**Issue by alloy** [relay-tools/relay-compiler-language-typescript#132]
Currently if you’d have a module that exports a single function that in turn commits a mutation, the module might be called something like `createConsignmentSubmission` after the function. This leads to the types we define to also be called `createConsignmentSubmission`, `createConsignmentSubmissionResponse`, `createConsignmentSubmissionVariables`. Should we capitalise those instead? Unsure what upstream does. 🤔

**Comment by kastermester** [comment]
I'm fairly certain the types are named after the mutation, not the file name, are they not?

**Comment by alloy** [comment]
Correct, but relay-compiler insists the operation is named after the module ♻️

**Comment by kastermester** [comment]
Is this only when using relay modern? I don't have any issues with a file named `changeProjectNodeProgress.ts` to contain the following operation:

```
mutation ChangeProjectNodeProgressMutation($input: ChangeProjectNodeProgressInput!) {
	changeProjectNodeProgress(input: $input) {
		projectNode {
			id
			version
			progress
			progressRollup
			modifiedAt
			trail {
				id
				__typename
				progress
				progressRollup
			}
		}
	}
}
```

**Comment by sibelius** [comment]
I don't think this is a good idea, I'd rather match the filename

**Comment by alloy** [comment]
@kastermester Must be then 🤷‍♂ 

@sibelius Yeah I guess you’re right, perhaps this should just be filed under “deal with my OCD”.
