### ISSUE TITLE
auto deploy fails to push to git repo

### ISSUE THREAD

**Issue by alloy** [relay-tools/relay-compiler-language-typescript#133]
I've tried a number of things, last being to have a single `.env` file with both NPM and GitHub tokens, as per [auto docs](https://github.com/intuit/auto/blob/114b3b335c49bce001f7c2b11af8c89bc8c85a57/docs/pages/getting-started.md#3-environment-variables), but while the NPM publish process still works the GitHub push process still fails.

**Comment by zephraph** [comment]
This is fixed now so I’ll close

**Comment by alloy** [comment]
Thanks @zephraph 🙏
