### ISSUE TITLE
Can we add instructions on how to contribute?

### ISSUE THREAD

**Issue by Stephen2** [relay-tools/relay-compiler-language-typescript#136]
I am having some thoughts about the handling of union types, and wanted to dig deeper.

Forked this repo, and tried to get started by running scripts, but got confused.

While `build` and `lint` appear to work, I couldn't understand `relay` `sync-fixtures` or `test`

I guess I'll keep digging but wanted to put hand up that I don't understand.  Maybe a quick paragraph in the readme about how to do testing would be great?

**Comment by maraisr** [comment]
That sounds like a great idea! Anything we can do to help - we're down for!

So you mentioned that you weren't able to run tests?

**Comment by Stephen2** [comment]
OK, maybe it's time for me to go to bed 😆 

I forked the repo, cloned it locally and I swear `test` was saying "No tests found"... But now cloning THIS repo the `test` command looks like it's doing it's thing.

OK, fine.

these 2 scripts don't work for me, and I don't know if they're important:
```
~/code/relay-compiler-language-typescript master$ yarn run relay
yarn run v1.19.0
$ node bin/relay-compiler.js --schema test/schema.graphql --src test/ --outputDir __generated__
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/stephen.pittman/code/relay-compiler-language-typescript/bin/relay-compiler.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~/code/relay-compiler-language-typescript master$ yarn run sync-fixtures
yarn run v1.19.0
$ rsync -avh --delete --stats --progress ../relay/packages/relay-compiler/language/javascript/__tests__/fixtures/flow-generator/**/*.graphql test/fixtures/type-generator
building file list ...
rsync: link_stat "/Users/stephen.pittman/code/relay-compiler-language-typescript/../relay/packages/relay-compiler/language/javascript/__tests__/fixtures/flow-generator/**/*.graphql" failed: No such file or directory (2)
0 files to consider

Number of files: 0
Number of files transferred: 0
Total file size: 0 bytes
Total transferred file size: 0 bytes
Literal data: 0 bytes
Matched data: 0 bytes
File list size: 13
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 29
Total bytes received: 20

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/main.c(996) [sender=2.6.9]
error Command failed with exit code 23.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Stephen2** [comment]
I guess `sync-fixtures` expects me to clone the latest `relay` repo into `../relay` ?

Not sure when/why I need to do that

**Comment by alloy** [comment]
The `relay` script requires the example app to have been bootstrapped. It’s a little involved and could do with some simplification, but I think it will require to update this repo to use yarn workspaces instead.

The `sync-fixtures` script is for when you know there are updated test fixtures in the upstream repo and you want to pull those into this repo. That shouldn’t be necessary right now, though.

**Comment by Stephen2** [comment]
point being I guess, it was hard to get in to running locally/debugging/contributing a little bit.

Probably my own ignorance, but the suggestion is a paragraph or 2 in README about how to help :)

Anyway, my actual problem I wanted to contribute to was improved somewhere between 4.3.0 and 6.0.0 so I'm gonna close this.

Thanks very much @maraisr and @alloy
