### ISSUE TITLE
Type errors in example app

### ISSUE THREAD

**Issue by alloy** [relay-tools/relay-compiler-language-typescript#15]
```
ts/__generated__/appQuery.graphql.ts(3,10): error TS2305: Module '"/Users/eloy/Code/React/typescript-relay-modern-compiler/example/node_modules/@types/relay-runtime/index"' has no exported member 'ConcreteRequest'.

3 import { ConcreteRequest } from 'relay-runtime';
           ~~~~~~~~~~~~~~~


ts/components/__generated__/TodoApp_viewer.graphql.ts(4,10): error TS2305: Module '"/Users/eloy/Code/React/typescript-relay-modern-compiler/example/node_modules/@types/relay-runtime/index"' has no exported member 'FragmentReference'.

4 import { FragmentReference } from "relay-runtime";
           ~~~~~~~~~~~~~~~~~


ts/__generated__/appQuery.graphql.ts(8,33): error TS2304: Cannot find name 'TodoApp_viewer_ref'.

8         readonly " $fragments": TodoApp_viewer_ref;
                                  ~~~~~~~~~~~~~~~~~~


ts/app.tsx(74,25): error TS2322: Type '{ viewer: any; }' is not assignable to type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.
  Type '{ viewer: any; }' is not assignable to type 'Props'.
    Property 'relay' is missing in type '{ viewer: any; }'.

74         return <TodoApp viewer={props.viewer} />;
                           ~~~~~~~~~~~~~~~~~~~~~


ts/components/TodoApp.tsx(56,21): error TS2322: Type '{ viewer: TodoApp_viewer; }' is not assignable to type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.
  Type '{ viewer: TodoApp_viewer; }' is not assignable to type 'Props'.
    Property 'relay' is missing in type '{ viewer: TodoApp_viewer; }'.

56           <TodoList viewer={this.props.viewer} />
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~


ts/components/TodoApp.tsx(57,40): error TS2322: Type '{ viewer: TodoApp_viewer; }' is not assignable to type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.
  Type '{ viewer: TodoApp_viewer; }' is not assignable to type 'Props'.
    Property 'relay' is missing in type '{ viewer: TodoApp_viewer; }'.

57           {hasTodos && <TodoListFooter viewer={this.props.viewer} />}
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~


ts/components/TodoList.tsx(49,9): error TS2322: Type '{ key: string; todo: { readonly id: string; readonly complete: boolean | null; readonly " $fragme...' is not assignable to type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.
  Type '{ key: string; todo: { readonly id: string; readonly complete: boolean | null; readonly " $fragme...' is not assignable to type 'Props'.
    Property 'relay' is missing in type '{ key: string; todo: { readonly id: string; readonly complete: boolean | null; readonly " $fragme...'.

49         key={node.id}
           ~~~~~~~~~~~~~50         todo={node}
   ~~~~~~~~~~~~~~~~~~~51         viewer={this.props.viewer}
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


ts/components/__generated__/TodoApp_viewer.graphql.ts(10,29): error TS2304: Cannot find name 'TodoListFooter_viewer_ref'.

10     readonly " $fragments": TodoListFooter_viewer_ref & TodoList_viewer_ref;
                               ~~~~~~~~~~~~~~~~~~~~~~~~~


ts/components/__generated__/TodoApp_viewer.graphql.ts(10,57): error TS2304: Cannot find name 'TodoList_viewer_ref'.

10     readonly " $fragments": TodoListFooter_viewer_ref & TodoList_viewer_ref;
                                                           ~~~~~~~~~~~~~~~~~~~


ts/components/__generated__/TodoList_viewer.graphql.ts(13,45): error TS2304: Cannot find name 'Todo_todo_ref'.

13                     readonly " $fragments": Todo_todo_ref;
                                               ~~~~~~~~~~~~~


ts/components/__generated__/TodoList_viewer.graphql.ts(20,29): error TS2304: Cannot find name 'Todo_viewer_ref'.

20     readonly " $fragments": Todo_viewer_ref;
                               ~~~~~~~~~~~~~~~
```

**Comment by kastermester** [comment]
There's two kind of errors here:

1. The typings for relay-runtime does not match what is expected
2. When we need to "import" a type and cannot (due to the relative path stuff we disabled) we still need a name for that type. The flow stuff works by simply declaring a type that is aliased to `any`.

I will look into number 2.

**Comment by alloy** [comment]
Yup. The ones described in 1 are already in this PR https://github.com/alloy/DefinitelyTyped/pull/1, but that PR first still needs to be amended based on your approach. Will you send a PR for that as well?

**Comment by kastermester** [comment]
I can yes - what about the names for the special properties used to make the type system work. Any changes we should make here?

The names are arbitrary no matter what we do I'd say - so its tough to say which ones would be best I think?

**Comment by alloy** [comment]
Ah yes, good point. I initially went with something like `*_ref` as well, but after integrating it into one of our apps I didn’t quite like the aesthetic of it and found the way it’s done in the upstream Flow typings somewhat nicer to read, the `$` immediately makes it clear that these are special things.

**Comment by kastermester** [comment]
I think naming the ref types with $ is fine. I was more thinking about the property names. I quite like the idea of getting them out of the auto completion list, perhaps we should just name them the same as they do in the flow implementation, but with a whitespace prefixed?

**Comment by alloy** [comment]
Oh yes yes, I absolutely agree with keeping them out of the auto-completion list!

Just out of curiosity, do you know if it’s documented behaviour or could it just be a TS language server/VS Code bug?

**Comment by kastermester** [comment]
I can't remember where I first saw it mentioned, but I would be surprised if it is documented - but I can try and look at the TS source code to see if it seems intentional.

**Comment by alloy** [comment]
I would be nice to have link to leave in a comment next to the code that generates the property name, but I’m ok with using undocumented behaviour too 👍

**Comment by kastermester** [comment]
I have some trouble finding the exact code in the repo, as it is quite large. However, it does kinda make sense that they exclude properties whose names aren't valid JS identifiers.

**Comment by alloy** [comment]
Ah yes, good point. A comment that says that would be enough.

**Comment by kastermester** [comment]
I will try to work on the PR for DT. I need to figure out how to deal with array types in the code for it. The flow type definitions do a bit with it, so I'll try to decipher that and see if I can replicate it for TS.

**Comment by alloy** [comment]
Not sure it helps with the situation you’re thinking of, but just in case this might be helpful https://twitter.com/kassens/status/946810603875729408

**Comment by kastermester** [comment]
I think we can close this for now? As far as I know we just have better typings to create (missing classic types as well as the awaitings of TS 2.8).

**Comment by alloy** [comment]
Sounds good 👍
