### ISSUE TITLE
Enums not generating correctly with Relay 8

### ISSUE THREAD

**Issue by mrtnzlml** [relay-tools/relay-compiler-language-typescript#164]
Hi, we tried to upgrade Relay to version 8 with this language plugin but the generated enums look a bit fishy, see:

```patch
@@ -2,7 +2,7 @@
 
 import { ReaderFragment } from "relay-runtime";
 import { FragmentRefs } from "relay-runtime";
-export type LabelColor = "BLUE" | "GRAY" | "GREEN" | "PURPLE" | "RED" | "YELLOW" | "%future added value";
+export type LabelColor = "%future added value" | "%future added value" | "%future added value" | "BLUE" | "GRAY" | "GREEN" | "PURPLE" | "RED" | "YELLOW" | "%future added value";
 export type Label_label = {
     readonly colorName: LabelColor | null;
     readonly name: string | null;
```

Notice the `%future added value` placeholder duplicates. Changelog which mentions the enums as well: https://github.com/facebook/relay/releases/tag/v8.0.0

Thanks for having a look! :)

**Comment by mrtnzlml** [comment]
Seems like it's not happening anymore - cannot reproduce it now. 🤔

**Comment by alloy** [comment]
Oof, good catch. Is this the only issue you have spotted? (In which case I assume there’s no actual fallout?)

**Comment by mrtnzlml** [comment]
@alloy Hi! It seems like that's the only issue so far. :)

**Comment by mrtnzlml** [comment]
Related PR: https://github.com/relay-tools/relay-compiler-language-typescript/pull/170

**Comment by sibelius** [comment]
does the PR solves your problem?

**Comment by mrtnzlml** [comment]
Not 100% sure (didn't try) but this error should be visible there when upgrading Relay (there is a test fixture for such enums). So I'd say yes. 🤞

**Comment by mrtnzlml** [comment]
Fixed here: https://github.com/relay-tools/relay-compiler-language-typescript/pull/173
