### ISSUE TITLE
TypeError: Cannot read property 'identifier' of undefined 

### ISSUE THREAD

**Issue by videni** [relay-tools/relay-compiler-language-typescript#165]
I created an issue [here](https://github.com/facebook/relay/issues/2971), seems this plugin doesn't work well with Relay 8.

**Comment by videni** [comment]
Can anyone  implement this feature ASAP? I really need it recently.

**Comment by sibelius** [comment]
Send a pull request, so we can review

**Comment by alloy** [comment]
@sibelius With the linked issue being closed, is this still relevant?

**Comment by sibelius** [comment]
we still need to upgrade to relay v8, maybe another issue for this

**Comment by alloy** [comment]
Perhaps. If this issue actually occurs when using v8 with the current plugin then I guess this issue is fine too.

FYI As I’m not working on any Relay projects atm, it would be best for others to contribute changes necessary for v8.

**Comment by videni** [comment]
this can be closed
