### ISSUE TITLE
Scalars types

### ISSUE THREAD

**Issue by pollend** [relay-tools/relay-compiler-language-typescript#181]
I have some scalars in my graphql scheme but they seem to get mapped to unknown. any clue how these types can be mapped to an typescript equivalent. is there some kind of configuration that isn't documented or something that can be added?

```
scalar DateTime

type SomeObject implements INode {
  id: ID!
  last_updated: DateTime!
}
```

**Comment by olso** [comment]
@pollend How did you fix it?

**Comment by olso** [comment]
Solved it by adding `relay-config` package

and adding

```js
// const typescript = require("relay-compiler-language-typescript");

module.exports = {
  // Configuration options accepted by the `relay-compiler` command-line tool and `babel-plugin-relay`.
  src: "./src",
  schema: "./schema.graphql",
  language: "typescript",
  extensions: ["ts", "tsx"],
  artifactDirectory: "./src/__generated__",
  // watch: false,
  // validate: true,
  customScalars: {
    Money: "String",
    DateTime: "String",
    BookingDate: "String",
    Time: "String",
    Date: "String",
  },
};
```

The whole experience of custom scalars is messy

I need to have them in 3 places!!!

api codegen, web codegen, and now relay config...

**Comment by haf** [comment]
So one has to add an extra package? Where's custom scalars documented?

**Comment by theseyi** [comment]
Thanks for this @olso ! Is this documented anywhere @olso ?

**Comment by olso** [comment]
@theseyi not sure where i found it, probably just browsing through docs and issues
