### ISSUE TITLE
unused `FragmentReference` import causes compile error when using "noUnusedLocals"

### ISSUE THREAD

**Issue by andsens** [relay-tools/relay-compiler-language-typescript#182]
[Given this reproduce](https://gist.github.com/andsens/2407142407bb9d3732bac0cf0ed8410b), the following part of the code 
https://github.com/relay-tools/relay-compiler-language-typescript/blob/4f9dbede475041623bb8009a90c98710f928f5fb/src/TypeScriptGenerator.ts#L476-L478

adds an unused `FragmentReference` import to `ComponentPaginationQuery.graphql.ts`. This causes the typescript compiler to fail when it is configured with `noUnusedLocals: true`.

**Comment by enisdenjo** [comment]
Previously, as a workaround, you simply open the artifact file and drop the unused import.

But, as of [Relay v9.1.0](https://github.com/facebook/relay/releases/tag/v9.1.0), this does not work anymore, because the compiler will just add it in as soon as it performs the compilation again.

**Comment by sibelius** [comment]
can somebody send a fix for this?

**Comment by enisdenjo** [comment]
@sibelius 👆
