### ISSUE TITLE
react-scripts forces tsconfig module to esnext

### ISSUE THREAD

**Issue by unludo** [relay-tools/relay-compiler-language-typescript#184]
Hi,

I follow the documentation and set tsconfig but `react-scripts start` changes dynamically tsconfig.
So, when a graphql request is being executed, babel is lost, and I get this:

> graphql: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `graphql`.

If you have a workaround I would be very happy if you share.

Thank you!

**Comment by renanmav** [comment]
When using CRA, you need to use babel-macro, [check this](https://relay.dev/docs/en/installation-and-setup.html#set-up-babel-plugin-relay).

```ts
import graphql from 'babel-plugin-relay/macro';
```

You can me it type safe [like this](https://github.com/renanmav/relay-examples-typescript/blob/master/issue-tracker/src/react-app-env.d.ts) too.
