### ISSUE TITLE
Jest fails when adding artifactDirectory to babel config

### ISSUE THREAD

**Issue by hyochan** [relay-tools/relay-compiler-language-typescript#191]
<img width="575" alt="Screen Shot 2020-06-09 at 11 29 08 AM" src="https://user-images.githubusercontent.com/27461460/84099406-7ffce680-aa44-11ea-9438-09cf63dba935.png">

Above is the result when I add 
```
[['relay', { artifactDirectory: './src/__generated__' }]],
```

to `babel.config.js`.

If I just add `relay`, the test doesn't fail. Any idea?

**Comment by renanmav** [comment]
I think this is related to `babel-plugin-relay`, not `relay-compiler-language-typescript`. Try to use it with just javascript. Does it still happen?

**Comment by maraisr** [comment]
I can take a look at this. Can you please provide me with a little more information, potentially a reproduction repo?

**Comment by hyochan** [comment]
@maraisr Thanks. This is currently happening in [pull request](https://github.com/dooboolab/hackatalk-mobile/pull/136).

I've not made proper integration with relay yet but you can generate the above case.

**Comment by devethan** [comment]
Followed by [this](https://relay.dev/docs/en/type-emission#single-artifact-directory), you can use jest without above error.

```json
// this is recommended config on docs
{
  "plugins": [
    ["relay", { "artifactDirectory": "./src/__generated__" }]
  ]
}
```

```json
// your config
{
  "plugins": [
    [['relay', { artifactDirectory: './src/__generated__' }]],
  ]
}
```

**Comment by hyochan** [comment]
@devethan Then [this documenet in relay-compiler-language-typescript](https://github.com/relay-tools/relay-compiler-language-typescript#configuration) should be fixed?

**Comment by devethan** [comment]
I added [review](https://github.com/dooboolab/hackatalk-mobile/pull/136/files?file-filters%5B%5D=.graphql&file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx&file-filters%5B%5D=.yml#r443282813) to your PR.

**Comment by hyochan** [comment]
Oh. I had 3 brackets. Thanks.
