### ISSUE TITLE
CRA 4 is forcing esnext as module system

### ISSUE THREAD

**Issue by nico159** [relay-tools/relay-compiler-language-typescript#219]
Hi,
CRA 4 started to force esnext as module system in the tsconfig, breaking the relay compiler TS support
https://github.com/facebook/create-react-app/blob/3a98ed1c2457f6f507652f7dfd52de00b0e3d6d7/packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js#L133

**Comment by naorzr** [comment]
@nico159 why did you close it? did you find a solution?

**Comment by Yiyue15** [comment]
I've got the same question here as well!
