### ISSUE TITLE
Move to relay-tools org?

### ISSUE THREAD

**Issue by alloy** [relay-tools/relay-compiler-language-typescript#26]
@kastermester Once we’re done and decide to publish, what do you think of moving to the https://github.com/relay-tools org so that people can more easily find it amongst other Relay tools?

**Comment by kastermester** [comment]
Sounds good! :) Should we just tag the owners of the organization here or do you know of the procedures to go through to make that happen?

**Comment by alloy** [comment]
I already have access, just sent you an invite!

**Comment by kastermester** [comment]
Thanks, got it and joined! :)

**Comment by alloy** [comment]
I’m going to point the homepage property of the 0.9.0 package that I’m going to cut to the relay-tools org. As such, mind transferring this repo there now?

**Comment by kastermester** [comment]
Done :)

**Comment by alloy** [comment]
Ace, thanks!
