### ISSUE TITLE
Migrate travis CI release process to GitHub actions

### ISSUE THREAD

**Issue by zephraph** [relay-tools/relay-compiler-language-typescript#308]
I'd forgotten that we used Travis for hooking in auto and was pretty confused there for a minute. This is something I'd be willing to take on as a general improvement that should make it a little easier to see what's going on.

**Comment by zephraph** [comment]
Hey @alloy I'll need you for this one. 

Can you go [to the settings](https://github.com/relay-tools/relay-compiler-language-typescript/settings/secrets/actions) and add an `NPM_TOKEN` repository secret to this repo? Will need that for perms to publish. Should look something like this when you're done: 

![image](https://user-images.githubusercontent.com/3087225/127951871-0c45f3a3-285f-4f4b-9a81-20db49039412.png)

You can use an automation token from NPM.

**Comment by alloy** [comment]
Done! 🙏
