### ISSUE TITLE
Why is it not releasing

### ISSUE THREAD

**Issue by n1ru4l** [relay-tools/relay-compiler-language-typescript#405]
@alloy @zephraph I merged https://github.com/relay-tools/relay-compiler-language-typescript/pull/269 and again nothing is happening... Every time I try to merge and release sth it does not work 😅

**Comment by zephraph** [comment]
Yep, sorry. I'll look into it and report the findings here.

**Comment by zephraph** [comment]
Looks like we're over limits on Travis

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

Seems like the last few builds had been fine. Probably time to finally do that migration to being fully on GitHub actions.

**Comment by zephraph** [comment]
I'll work on this in #308.

**Comment by n1ru4l** [comment]
@zephraph Seems like there is still some environmant variable missing for github releases

**Comment by zephraph** [comment]
Yep, I’ll address it.
