### ISSUE TITLE
New release with latest plugin-version

### ISSUE THREAD

**Issue by arieldf** [relay-tools/relay-compiler-language-typescript#41]
@alloy Thanks a lot for the great work here. Will there be a new release of this library with the plugin-updates from today?

Best regards,
Ariel

**Comment by alloy** [comment]
Oh great question! Actually the way I’ve been using it, due to various transitive dependencies that really should all be using the same versions, is by using [yarn’s resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) feature, which is also how it’s being used in [the example app’s setup](https://github.com/relay-tools/relay-compiler-language-typescript/blob/aec5c441a9a0784dcf02ea4cd186afff7df8e1ef/example/package.json#L10-L17).

Hope that helps!

**Comment by arieldf** [comment]
@alloy Great! Thanks - I did not understand the resolutions correctly. Thanks again for the great efforts here

**Comment by alloy** [comment]
Thanks for testing and please give us any feedback on the PR whilst things have not been merged yet!

**Comment by arieldf** [comment]
@alloy So far things are working nice! I do get the errors below when starting the app, but things seem to work as expected.

ERROR in project/packages/modules/example/ts/app.tsx(74,25):
TS2322: Type '{ viewer: any; }' is not assignable to type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.
  Type '{ viewer: any; }' is not assignable to type 'Props'.
    Property 'relay' is missing in type '{ viewer: any; }'.
ERROR in project/packages/modules/example/ts/components/TodoApp.tsx(56,21):
TS2322: Type '{ viewer: TodoApp_viewer; }' is not assignable to type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.
  Type '{ viewer: TodoApp_viewer; }' is not assignable to type 'Props'.
    Property 'relay' is missing in type '{ viewer: TodoApp_viewer; }'.
ERROR in project/packages/modules/example/ts/components/TodoApp.tsx(57,40):
TS2322: Type '{ viewer: TodoApp_viewer; }' is not assignable to type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.
  Type '{ viewer: TodoApp_viewer; }' is not assignable to type 'Props'.
    Property 'relay' is missing in type '{ viewer: TodoApp_viewer; }'.
ERROR in project/packages/modules/example/ts/components/TodoList.tsx(49,9):
TS2322: Type '{ key: string; todo: { readonly id: string; readonly complete: boolean | null; }; viewer: TodoLis...' is not assignable to type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.
  Type '{ key: string; todo: { readonly id: string; readonly complete: boolean | null; }; viewer: TodoLis...' is not assignable to type 'Props'.
    Property 'relay' is missing in type '{ key: string; todo: { readonly id: string; readonly complete: boolean | null; }; viewer: TodoLis...'.
Version: typescript 2.6.2

**Comment by alloy** [comment]
Are you using the latest versions of the `@types/react-relay` and `@types/relay-runtime` packages?

**Comment by alloy** [comment]
Or can you otherwise include a failing code snippet?

**Comment by arieldf** [comment]
@alloy, so this turned out to be a clash with typings. I removed the relay-runtime and react-relay types and it works (I am using latests React).

**Comment by alloy** [comment]
Did you remove them completely? Or did you remove the clashing ones?

**Comment by arieldf** [comment]
I removed the types for relay-runtime and react-relay and it is working nicely. Would be nice to have the types, but in my case I am fine without.

**Comment by alloy** [comment]
The typings should be working, though, it does for us at least. Could you try to create a minimal example project that exhibits the problem?
