### ISSUE TITLE
Support --noImplicitAny

### ISSUE THREAD

**Issue by cvle** [relay-tools/relay-compiler-language-typescript#48]
I'm using `--noImplicitAny`, and I can't compile when I include the generated mutation files.
Is there a way to add the required `: any` and `as any` annotations to the generated files?

E.g.
```ts
const node: ConcreteRequest = (function(){
var v0: any = [],
v1: any = [...];
return {
  "kind": "Request",
   ...
} as any)();
```

Thanks for the efforts

**Comment by orta** [comment]
This makes sense, yeah, send a PR 👍

**Comment by cvle** [comment]
I tried and I don't understand it quiet yet.. any hints to help me out?

**Comment by alloy** [comment]
Hmm, yeah, this isn’t that easy right now. The plugin currently only operates on the types for the resulting GraphQL selections, not the artefact AST. The artefact AST comes in as just a large string from relay-compiler [here](https://github.com/relay-tools/relay-compiler-language-typescript/blob/3e732badeb8f0522f1528a0b21a1e1ca121511bd/src/formatGeneratedModule.ts#L23), so the only way I could currently see this work is if we were to parse that text and regenerate it with the `any` typings, but that _seems_ a little costly. Maybe we can determine if the `noImplicitAny` compiler flag is enabled and only then do the parsing/regeneration?

In any case, that’s where you should start with this.

**Comment by kastermester** [comment]
It should be possible to use the TypeScript parser / emitter to inject the needed type annotations - although if you haven't used this API before it might be a bit tricky. I don't think it will be *that* costly using the TS API for this, it should be kinda fast - but obviously this would need to be verified.

**Comment by timjacobi** [comment]
I hacked it together today.

```
function addAsAnyToObjectLiterals(oldSource){
    const ts = require("typescript");

    function transformer(context){
        return function transform(node){
            function visit(node){
                if(node.kind === ts.SyntaxKind.ObjectLiteralExpression){
                    return ts.createAsExpression(node, ts.createTypeReferenceNode('any', []));
                }
                return ts.visitEachChild(node, visit, context);
            }
            return ts.visitNode(node, visit);
        }   
    }

    const source  = ts.createSourceFile('', oldSource);

    const result = ts.transform(source, [transformer]);

    const printer = ts.createPrinter();
    const newSource = printer.printFile(result.transformed[0]);
    return newSource;
}
```

**Comment by alloy** [comment]
Nice and simple 👌 And where are you adding this into your pipeline?

**Comment by sibelius** [comment]
should this be an option for relay compiler?

**Comment by timjacobi** [comment]
@alloy I manually added it [here](https://github.com/relay-tools/relay-compiler-language-typescript/blob/3e732badeb8f0522f1528a0b21a1e1ca121511bd/src/formatGeneratedModule.ts#L23) in my project and it worked. If you want I can look into integrating it into this library.

**Comment by alloy** [comment]
@sibelius I don’t think so, it’s a project wide TS setting, so my opinion is that we should fetch it from the project’s tsconfig (or perhaps there’s a runtime test for tsc options.)

@timjacobi Yeah that would be much appreciated! (And only do so when the option is enabled, as per above.)

**Comment by timjacobi** [comment]
@alloy sounds good! I'm travelling this week but will get started on the PR after

**Comment by alloy** [comment]
Closed by https://github.com/relay-tools/relay-compiler-language-typescript/pull/83
