### ISSUE TITLE
Invalid AST Node error with graphql@16

### ISSUE THREAD

**Issue by stasyaner** [relay-tools/relay-compiler-language-typescript#507]
Hello.

I'm getting the below error with graphql@16:
```bash
yarn run v1.22.17
$ relay-compiler

Writing ts
ERROR:
Invalid AST Node: { kind: "Root", operation: "query", loc: { kind: "Source", start: 3, end: 54, source: [Source] }, metadata: null, name: "AppQuery", argumentDefinitions: [], directives: [], selections: [[Object]], type: Query }.
error Command failed with exit code 100.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It works with graphql@15.7.2.
I've created [a repo](https://github.com/stasyaner/graphql-relay-issue) to see it in action.

Thanks.

**Comment by saihaj** [comment]
I think this is an issue with relay compiler don’t believe it supports v16 yet. cause it still uses v15 in peerDep https://github.com/facebook/relay/blob/5e3851fa593fef85fbf57e2644c578a1240282cc/packages/relay-compiler/package.json#L37

**Comment by stasyaner** [comment]
@saihaj, may be. Thanks.
Let this issue be a reference for anybody else facing the same.
