### ISSUE TITLE
Typescript 4.5 type generation is broken

### ISSUE THREAD

**Issue by VictorGlindasPaf** [relay-tools/relay-compiler-language-typescript#513]
After updating toTypescript 4.5, I'm getting broken types output from the relay compiler.
I'm on version `14.3.0` of `relay-compiler-language-typescript`.

```ts
// Typescript 4.4
import { FragmentRefs } from "relay-runtime";
```
```ts
// Typescript 4.5
import { FragmentRefs as } from "relay-runtime";
```

**Comment by piotrblasiak** [comment]
Same here

**Comment by saihaj** [comment]
Yeah CI is breaking here for the upgrade  https://github.com/relay-tools/relay-compiler-language-typescript/pull/512 @

**Comment by tszarzynski** [comment]
We started observing similar issue using TS 4.3.5 and v.14.3.0. 

It currently works fine with 
```
"relay-compiler-language-typescript": "^14.0.0",
"typescript": "~4.4.4",
```

**Comment by Strandedpirate** [comment]
Same error here too. In my case I had to nuke my `yarn.lock` and re-install and then this error started occurring. The `yarn.lock` file got totally re-written, so I just undid the changes, did another `yarn install` and it stopped generating the bad graphql files.

**Comment by VictorGlindasPaf** [comment]
> Same error here too. In my case I had to nuke my `yarn.lock` and re-install and then this error started occurring. The `yarn.lock` file got totally re-written, so I just undid the changes, did another `yarn install` and it stopped generating the bad graphql files.

If you revert the lock file and install, that will install the old version. So it's no wonder that it stopped generating the bad files since you didn't actually update anything.
