### ISSUE TITLE
[discussion] Could this library also generate mock data for a relay component?

### ISSUE THREAD

**Issue by orta** [relay-tools/relay-compiler-language-typescript#56]
E.g. could there be a feature that causes the relay to create mocked data for a particular component. 

It's a lot of files, sure, but it would make the initial buildout much easier (and keeps those initial data stubs up to date as the component / fragments change )

**Comment by alloy** [comment]
Can you expand a bit on the details?

graphql-tools’ schema mocking already does fake data generation based on the types, which we’ve [started using in Reaction](https://github.com/artsy/reaction/pull/1065), so that might cover everything you have in mind already.

**Comment by orta** [comment]
Yep - that is the perfect abstraction, great work @robrichard 

Gonna close.
