### ISSUE TITLE
Emitted types break default setup when colocating artefacts.

### ISSUE THREAD

**Issue by alloy** [relay-tools/relay-compiler-language-typescript#58]
As reported by @ckknight https://twitter.com/ckknight/status/1026846806930468864, it appears that when one does **not** enable a single artefact directory –and thus fragment references get typed as `any` rather than being imported from other artefacts– TS is [unable to work with the types](https://www.typescriptlang.org/play/index.html#src=declare%20const%20_Fragment%24ref%3A%20unique%20symbol%0D%0Atype%20Fragment%24ref%20%3D%20typeof%20_Fragment%24ref%0D%0Aconst%20ref%3A%20Fragment%24ref%20%3D%20%7B%7D%20as%20any):

```
Type 'any' is not assignable to type 'unique symbol'.
```

I haven’t yet been able to find any issues on the TS issue tracker about this, so unsure right now how to proceed.

Maybe we should not emit the fragment reference typings when not using the single artefact directory feature, because those typings are moot in that case anyways?

**Comment by kastermester** [comment]
I see now.

This does indeed seem quite weird. I think there's still value in emitting the types (just as flow does) but emit those as `any` as well (ie. not as a unique symbol type). 

Ie. for the above linked playground we should emit something [like this instead](https://www.typescriptlang.org/play/index.html#src=declare%20const%20_Fragment%24ref%3A%20any%3B%0D%0Atype%20Fragment%24ref%20%3D%20typeof%20_Fragment%24ref%0D%0Aconst%20ref%3A%20Fragment%24ref%20%3D%20%7B%7D%20as%20any)

**Comment by alloy** [comment]
Fair, we could do that too. What’s your thought for there still being value? Just as a named label that could help indicate what reference is required?

**Comment by kastermester** [comment]
I just edited in my thoughts as you replied, realised it might not be obvious why it would be a good idea.

**Comment by alloy** [comment]
Agreed. I’ll file an issue.
