### ISSUE TITLE
Issue with Nested Fragment Containers

### ISSUE THREAD

**Issue by kevinhughes27** [relay-tools/relay-compiler-language-typescript#63]
First - Thanks for all your work on this :heart:  

I'm running into an issue with nested Fragment Containers and types after updating to 1.1.0.

My components are like this:
```
QueryRenderer
  FragmentContainerOne
    ...
    FragmentContainerTwo
```

My query contains both fragments:

```
query ContainerQuery() {
  foo {
    ...FragmentContainerOne_foo        
  }
  bar {
    ...FragmentContainerTwo_bar
  }
}
```

FragmentContainerOne works fine and has the following Props:

```
interface Props {
  foo: FragmentContainerOne_foo;
  bar: FragmentContainerTwo_bar;
}
```

When I go to pass `bar` into FragmentContainerTwo I get a type error:

```
Type 'ReadonlyArray<{ readonly id: string; readonly name: string; readonly " $refType": any; }>' is not assignable to type 'ReadonlyArray<_FragmentRefs<any>>'.
  Type '{ readonly id: string; readonly name: string; readonly " $refType": any; }' is not assignable to type '_FragmentRefs<any>'.
    Property '" $fragmentRefs"' is missing in type '{ readonly id: string; readonly name: string; readonly " $refType": any; }'.
```

Sorry this one is not edited to be a generic example since I think its more useful to have the exact error and my actual type is pretty simple.

If you've got any ideas let me know and I am happy to help figure this out. I can also create an example to reproduce if nothing jumps out at you from my description.

**Comment by alloy** [comment]
Thanks for the kind words!

At a glance it seems like it may be related to this change https://github.com/relay-tools/relay-compiler-language-typescript/pull/61. I take it you are not using a single artefact directory, but rather the default colocated ones? And so am I right in understanding that with v1.0.x of this plugin it didn’t break?

While this should definitely work and thus may need fixing, I’d suggest you use the [single artefact directory feature](https://github.com/relay-tools/relay-compiler-language-typescript/blob/master/README.md#relay-compiler) anyways, because that will allow you to have type checking on your fragment references work.

**Comment by kevinhughes27** [comment]
Yes I am using a single artefact directory.

**Comment by alloy** [comment]
Oh, then those `any` types are really surprising to me. In that case, a repro would be very helpful.

**Comment by kastermester** [comment]
Without looking too much into this this part of your issue description looks strange to me:

> FragmentContainerOne works fine and has the following Props:

```
interface Props {
  foo: FragmentContainerOne_foo;
  bar: FragmentContainerTwo_bar;
}
```

If this is the props for the FragmentContainerOne it should look like this:

```
interface Props {
  foo: FragmentContainerOne_foo;
  bar: FragmentContainerOne_bar;
}
```

With that said - the `any` types in the error message are confusing me quite a bit. If this is simply a misunderstanding then I'd also very much like to see a repro (link to some github repository exhibiting the error would do). Thanks! :)

**Comment by alloy** [comment]
Good spot @kastermester 👍 

I’m thinking that as this component may be mixing fragments from other modules, maybe the case is similar to https://github.com/relay-tools/relay-compiler-language-typescript/issues/59#issuecomment-416975132 ?

**Comment by kevinhughes27** [comment]
I'm trying to pass the props all the way down to the second fragment container. The first one only needs them in order to pass them down. Maybe this is wrong? It's my first relay app (also first typescript project). Thanks for the responses I'll make an example repo!

**Comment by kevinhughes27** [comment]
Here you go!

https://github.com/kevinhughes27/nested_fragment_issue

```
src/FragmentOne.tsx:17:22 - error TS2322: Type 'ReadonlyArray<{ readonly id: string; readonly name: string; readonly " $refType": unique symbol; }>' is not assignable to type 'ReadonlyArray<_FragmentRefs<unique symbol>>'.
  Type '{ readonly id: string; readonly name: string; readonly " $refType": unique symbol; }' is not assignable to type '_FragmentRefs<unique symbol>'.
    Property '" $fragmentRefs"' is missing in type '{ readonly id: string; readonly name: string; readonly " $refType": unique symbol; }'.

17         <FragmentTwo bar={this.props.bar} />
```

**Comment by kevinhughes27** [comment]
Thanks for response! I might be missing another pattern in my app since the main reason for doing this was to avoid a query waterfall in this component. I'll do as you've suggested to fix my types for now. And you are correct this app is in the process of being remodelled as a graph and there are few awkward spots until the old code is fully deprecated :)

I'll close the issue.

**Comment by alloy** [comment]
> I might be missing another pattern in my app since the main reason for doing this was to avoid a query waterfall in this component.

I’m not sure if I fully understand this. My suggested change isn’t going to lead to more queries being performed, it’s still 1 query once merged by Relay.

**Comment by kevinhughes27** [comment]
Oh sorry your suggestion won't. I meant the general need for 2 root query types. Does that make sense?

**Comment by alloy** [comment]
Ah yep, gotcha 👍
