### ISSUE TITLE
React Hot Loader can't load generated artifacts

### ISSUE THREAD

**Issue by kalekseev** [relay-tools/relay-compiler-language-typescript#67]
Hi @alloy, thanks for the project.
I've tried it with my project and I get the following error when I use webpack-dev-server with react hot loader:
![screenshot from 2018-09-06 00-16-38](https://user-images.githubusercontent.com/367259/45121753-b8cea400-b16a-11e8-8e80-247386ccf263.png)
This error happen on page refresh, on HMR the page renders without such problems.
I would appreciate any ideas how that can be mitigated.

**Comment by alloy** [comment]
Hmm, these are all types so shouldn’t even really make their way to the browser. I.e. they should get compiled away entirely.

**Comment by kalekseev** [comment]
@alloy it seems like react hot module not always compile __generated__ directory, I found a similar issue https://github.com/gaearon/react-hot-loader/issues/1032. I assume we can't do match with that until we have types in generated files, maybe we should mention that issue in readme though.
