### ISSUE TITLE
Figure out how to do scalar type mappings

### ISSUE THREAD

**Issue by kastermester** [relay-tools/relay-compiler-language-typescript#70]
Right now we transform non-standard scalar types to `any`.

It should be somewhat straight forward to allow this to be user configurable in such a way that a user can specify that `Email` should be a `string` etc.

This is just an issue to keep track of the idea - and to open up the discussion for possible implementation details.

Things to consider:

* Should we just do a simple type name -> string config (ie `{"Email": "string"}`) or should we allow for more complex scenarios (ie. importing types from other modules which is then the actual type?)
* Where do we configure this? Some static file, or?
* Anything else?

**Comment by alloy** [comment]
In terms of a sanctioned entry-point for this (i.e. not forking the `relay-compiler` bin), I created this ticket https://github.com/facebook/relay/issues/2518

**Comment by pebeka** [comment]
as facebook/relay#2518 is released, one proposal to support importing types from other modules:
```typescript
const customScalars = {
  MyType: {
    type: 'MyType',
    module: '../myModule'
  },
  MySimpleString: 'String'  
}
```
this will add 
```typescript
import { MyType } from '../myModule';
```
in the generated file

**Comment by alloy** [comment]
@pebeka Interesting! This is something that should be discussed upstream imo. Mind opening a ticket on the FB/relay repo?

**Comment by pebeka** [comment]
https://github.com/facebook/relay/issues/2830

**Comment by maraisr** [comment]
Technically speaking you can map them in `customScalars`, like `Email: 'Email'`, and in your tsconfig have a global.d.ts or something file, that declares/exposes those types. And imo this is a better approach, and heck you can generate that too.

**Comment by alloy** [comment]
Hmm, the OP is supported now by https://github.com/facebook/relay/issues/2518 being done, right?

@maraisr I’m unsure what part of the thread you are replying to, though, can you clarify?
