### ISSUE TITLE
handling null from store.delete

### ISSUE THREAD

**Issue by mattkrick** [relay-tools/relay-compiler-language-typescript#71]
- Say I have a `Menu: [Dessert!]!`
- I get back `[{id: 'cakes'}, {id: 'pies'}]` from the server
- then in my updater, i call `store.delete('cakes')`
- Now I have `[null, {id: 'pies'}]` even though my typing says Dessert is guaranteed

how do you guys handle this? 
is there some secret way to clean up all arrays & connections outside of the view layer?
should the type always list a possible `null`?

**Comment by mattkrick** [comment]
oh nice, that's how i do it today-- the mutation payload includes the primary key removed & a foreign key which I can match with the name of every connection & list it can possibly belong to.

The tension is that the usage of a public API method (store.delete) can render a static type invalid, which kinda defeats the purpose of types. is there something we can do, or should it just be a rule to never use  this method?

**Comment by kastermester** [comment]
Well first I'd test whether this is true when using Relay with flow (which I'm almost certain it is) - if that's the case then this issue should be posted in the Relay repo itself. We don't really control how the APIs work, we've only tried to replicate what is happening for Flow and port it to TypeScript.

**Comment by alloy** [comment]
> the relay backlog black hole

😞 

As for the best practice, I can’t really offer any advice offhand, as our front-end apps only do the CRU part of CRUD atm, so would also have to play with an example app.
