### ISSUE TITLE
Support Relay v2.0.0

### ISSUE THREAD

**Issue by johntran** [relay-tools/relay-compiler-language-typescript#73]
Hi there,

At the time of writing this issue, Relay is on 1.7.0-rc.1, so it is a little early to fix.

## First Problem

So I'm testing out the latest master branch of FB with persisted queries, and I'm running into the following error 

```
> relay-compiler --src ./client --schema server/graphql/schema.graphql --extensions=js --extensions=tsx --extensions=ts --language typescript --persist --persist-output ./server/queryMap.json

HINT: pass --watch to keep watching for changes.

Writing ts
ERROR:
Error writing modules:
TypeError: Cannot read property 'indexOf' of undefined
    at /node_modules/relay-compiler-language-typescript/lib/TypeScriptTypeTransformers.js:93:73
    at Array.filter (<anonymous>)
    at transformNonNullableInputType (/node_modules/relay-compiler-language-typescript/lib/TypeScriptTypeTransformers.js:93:14)
    at Object.transformInputType (/node_modules/relay-compiler-language-typescript/lib/TypeScriptTypeTransformers.js:62:16)
    at /node_modules/relay-compiler-language-typescript/lib/TypeScriptGenerator.js:296:82
    at Array.map (<anonymous>)
    at generateInputVariablesType (/node_modules/relay-compiler-language-typescript/lib/TypeScriptGenerator.js:295:99)
    at Object.Root (/node_modules/relay-compiler-language-typescript/lib/TypeScriptGenerator.js:174:42)
    at Object.visit (/node_modules/graphql/language/visitor.js:254:26)
    at Object.visitIR [as visit] (/node_modules/graphql-compiler/lib/GraphQLIRVisitor.js:32:29)
```

Seems to be related to this line:
https://github.com/relay-tools/relay-compiler-language-typescript/blob/master/src/TypeScriptTypeTransformers.ts#L137

When I console.log `state`, the shape is now

```
{
  customScalars: {},
  existingFragmentNames: {},
  generatedInputObjectTypes: { DonationUpdateInput: 'pending' },
  generatedFragments: {},
  usedEnums: {},
  usedFragments: {},
  useHaste: false,
  useSingleArtifactDirectory: false,
};
```

Where `DonationUpdateInput` is a GraphQL Mutation Input.

It seems like `inputFieldWhiteList` is no longer a part of `TypeGeneratorOptions`

https://github.com/facebook/relay/blob/4343e80b48ad21d7bc40b57abdcb9acb751c45b3/packages/relay-compiler/language/RelayLanguagePluginInterface.js#L173

Because it was renamed to `optionalInputFields`

https://github.com/facebook/relay/commit/1755b04819b12b7b452ee327ed3156cc90ad0a3f

Renaming all instances of `inputFieldWhiteList` to `optionalInputFields` fixed it for me.

You can check out the changes here: https://github.com/ONEHOPEWINE/relay-compiler-language-typescript/commit/120f447c0fb397ff3b90a8ab030323115cbaec0e

## Second Problem

After applying the above fix, only Queries (that are used for the third parameter for `createRefetchContainer`) and Mutations are able to be parsed. All other fragments are not parsed, which includes the second parameter of RefetchContainer & createFragmentContainer, where a GQL query is a value to a key that is a React prop name. Not sure how to go forward from here.

Build files for persisted queries if you are curious. It requires React 16.5.2 because RelayContainer hooks into React.context.unstable_read. Its currently breaking for my use case because we use found-relay, which mutates the Relay context, and it seems like the Relay team are migrating to the new React.context API: https://github.com/ONEHOPEWINE/relay/releases/tag/1.7.1-rc.1

**Comment by alloy** [comment]
That renaming of `inputFieldWhiteList` to `optionalInputFields` looks good to me, care to make a PR?

As for the second issue, that seems a bit more suspect to me. Could you try to reproduce it by upgrading the example app in this repo to 1.7.0?

**Comment by johntran** [comment]
I'm fine with making a PR. Couple questions:

- Would you want it to be backwards compatible?

It would look like

```
const props = Object.keys(fields)
  .map(key => fields[key])
  .filter(
    field =>
      // Relay 1.6.2 and below
      (state.inputFieldWhiteList &&
        state.inputFieldWhiteList.indexOf(field.name) < 0) ||
      // Relay 1.7.0
      (state.optionalInputFields &&
        state.optionalInputFields.indexOf(field.name) < 0),
  );
```

- Is adding `optionalInputField` as an optional type and making inputFieldWhiteList an optional type ok?

**Comment by kastermester** [comment]
@johntran Idk about @alloy - but personally I don't see the need to make it backwards compatible. Relay does not officially support this plugin before v1.7.x - it was only supported through a fork that @alloy has maintained. I do think we need to worry as much as possible about backwards compatibility going forward though.

**Comment by alloy** [comment]
Due to other reasons upgrading to the latest relay isn’t trivial for us, but until any other new features/big fixes would be added there’s also no real reason for us to upgrade the plugin, so I’m fine with no backwards compatibility for this change 👍
