### ISSUE TITLE
artifactDirectory command not working

### ISSUE THREAD

**Issue by jgfidelis** [relay-tools/relay-compiler-language-typescript#75]
My project compiles the typescript files in the `src` folder and writes it to a `outputs` folder.

It always generates the `__generated__` folder inside my `src` folder, I may be wrong but I thought the `artifactDirectory` should be used to specify on where everything should be written to.

Here is my `yarn relay`:
`"relay": "relay-compiler --src ./src --schema schema.graphql --extensions=tsx --extensions=ts --language typescript --artifactDirectory ./outputs/__generated__",`

My `.babelrc`:
```
...
"plugins": [
    "@babel/plugin-transform-modules-commonjs",
    ["relay", { "artifactDirectory": "./outputs/__generated__" }]
  ]
```

I am using:
```
"react-relay": "^1.6.2",
 "relay-runtime": "1.7.0-rc.1"
"babel-plugin-relay": "^1.6.2",
"relay-compiler": "^1.6.2",
 "relay-compiler-language-typescript": "^1.1.1",
```

The `__generated__` is always compiled at `src/__generated__` and so the app doesn't start.

Am I missing something?

**Comment by alloy** [comment]
I don’t completely follow if your TS artifacts are created or not and why your app doesn’t start, can you elaborate on that?

Also, can you make sure to use 1.7.0-rc.1 for all the relay dependencies?

**Comment by jgfidelis** [comment]
Hey! Sorry for the confusion! I am not experienced enough in relay and may be getting some concepts confused.

I have a App.tsx in my `src` folder. After running `tsc`, I get a `outputs` folder with the transpiled `.js` files. My `index.js` imports the `App` component from `outputs/App`. Is this kind of structure supported by this plugin?

When I run `yarn relay`, and run my app, I get an red screen saying I do not have `__generated__` folder in my `outputs` folder:
<img width="547" alt="screen shot 2018-10-28 at 10 44 46" src="https://user-images.githubusercontent.com/4925068/47616659-b15ab580-da9e-11e8-9619-66ef567acf71.png">

Right now I am thinking: The correct thing should be: get a `__generated__` folder in my `src` folder so I can access the generated types and then all copy them to the `outputs` folder as well.

Is that more clear?

`Also, can you make sure to use 1.7.0-rc.1 for all the relay dependencies?`

How is the best way to guarantee this?

**Comment by sibelius** [comment]
check https://github.com/entria/entria-fullstack for examples using typescript without having a single artifact directory

**Comment by alloy** [comment]
@jgfidelis Sorry for missing this. I'm sure you're no longer dealing with this (and as such I'll close it too , but feel free to re-open); but your issue seems mostly related to your build process. If you're generating the artefacts into `src` and _then_ running `tsc`, I would expect compiled versions of the artefacts to show up in `outputs` as well.
