### ISSUE TITLE
noFutureProofEnums option not working

### ISSUE THREAD

**Issue by steida** [relay-tools/relay-compiler-language-typescript#80]
Btw, thank you a lot for this library!

**Comment by sibelius** [comment]
Can you provide more info? In which version?

**Comment by steida** [comment]
In master: https://github.com/relay-tools/relay-compiler-language-typescript/blob/d30921c693097558a921071e802387fa09f07dcc/src/TypeScriptGenerator.ts#L578

**Comment by sibelius** [comment]
it should be easy to get this working

https://github.com/facebook/relay/search?q=noFutureProofEnums&unscoped_q=noFutureProofEnums

**Comment by alloy** [comment]
Ah good catch! Yeah, like @sibelius says, a PR for this should be simple enough and would be much appreciated.

**Comment by artola** [comment]
@sibelius might be a bit more ... as shown in the [upstream](https://github.com/facebook/relay/commit/1e87e43add7667a494f7ff4cfa7f03f1ab8d81a2).

noFutureProofEnums:

- https://github.com/facebook/relay/blob/f54557df14f992ce175153913736eed3e2419d7c/packages/relay-compiler/language/javascript/RelayFlowGenerator.js#L260
-https://github.com/facebook/relay/blob/f54557df14f992ce175153913736eed3e2419d7c/packages/relay-compiler/language/javascript/RelayFlowGenerator.js#L523

should not be more than 3-4 small blocks.

**Comment by sibelius** [comment]
Feel free to contribute

**Comment by artola** [comment]
@sibelius done: https://github.com/relay-tools/relay-compiler-language-typescript/pull/82

**Comment by alloy** [comment]
👍
