### ISSUE TITLE
`getEnumDefinitions` with rare "%future added value"

### ISSUE THREAD

**Issue by artola** [relay-tools/relay-compiler-language-typescript#81]
For example, using `github` graphql `schema.graphql`:
```ts
"""The possible states of an issue."""
enum IssueState {
  """An issue that is still open"""
  OPEN

  """An issue that has been closed"""
  CLOSED
}
```

It is generated in the following type, containing an extra and rare ` "%future added value"`.
```ts
export type IssueState = "CLOSED" | "OPEN" | "%future added value";
```

Source code: https://github.com/relay-tools/relay-compiler-language-typescript/blob/0a1fb9e492f0f45be9eaf9c550f19cc329bada16/src/TypeScriptGenerator.ts#L578

Has this extra entry in the alias some especial meaning? It seems error prone.

**Comment by sibelius** [comment]
This is to be type safe for future enum values

you could add more enum types for your graphql schema and it won't break old apps

**Comment by alloy** [comment]
For more info see eg this upstream issue https://github.com/facebook/relay/issues/2351

**Comment by artola** [comment]
@sibelius @alloy  thanks for your prompt reply. From my point of view, a type system makes sense when you enforce it, and this kind of entry is not needed as stated in the upstream issue.
Anyway, see the code introduced in the upstream where is possible to use the flag `noFutureProofEnums` to avoid them.

https://github.com/facebook/relay/blob/f54557df14f992ce175153913736eed3e2419d7c/packages/relay-compiler/language/javascript/RelayFlowGenerator.js#L535

**Comment by alloy** [comment]
Yup, that simply wasn’t ported over yet because we don’t use that option. A tissue for this exists https://github.com/relay-tools/relay-compiler-language-typescript/issues/80

**Comment by artola** [comment]
@alloy Sorry I did not see #80 ... absolutely same.
