### ISSUE TITLE
Upstream RelayCompilerPublic change, rename to index.js

### ISSUE THREAD

**Issue by thoughtbyte** [relay-tools/relay-compiler-language-typescript#95]
Flagging an issue for future reference, this was merged recently into `relay`:
https://github.com/facebook/relay/pull/2677

This will break importing here: https://github.com/relay-tools/relay-compiler-language-typescript/blob/master/src/TypeScriptGenerator.ts#L6

Happy to open PR when a new release is cut with this change.

**Comment by sibelius** [comment]
this broke https://github.com/facebook/relay/issues/2710

**Comment by html-krit** [comment]
can it be fixed aspa plz guys!

**Comment by html-krit** [comment]
thanks!
