### ISSUE TITLE
Support relay-compiler@3.0.0

### ISSUE THREAD

**Issue by lumio** [relay-tools/relay-compiler-language-typescript#96]
Hey!

Just wanted to mention that `react-relay@3.0.0` and `relay-compiler@3.0.0` are out and the latest version of this package won't work with it

**Comment by alloy** [comment]
Thanks for logging this. Can you please add some more details about what exactly isn’t working?

**Comment by sibelius** [comment]
it is working fine for me on v3

**Comment by lumio** [comment]
I just wanted to post the error message. However, I think the aura of @sibelius just fixed it 😄 
It probably was just a `node_module` glitch when upgrading.

Sorry guys and thanks for the quick response
